# Generated by Django 4.1.4 on 2023-01-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_categorymodel_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='user',
        ),
    ]
